/*
 * GitPushr.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using GitPushr.Standard.Controllers;
using GitPushr.Standard.Http.Client;
using GitPushr.Standard.Utilities;

namespace GitPushr.Standard
{
    public partial class GitPushrClient
    {

        /// <summary>
        /// Singleton access to Bitbucket controller
        /// </summary>
        public BitbucketController Bitbucket
        {
            get
            {
                return BitbucketController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Github controller
        /// </summary>
        public GithubController Github
        {
            get
            {
                return GithubController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Git controller
        /// </summary>
        public GitController Git
        {
            get
            {
                return GitController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Jobs controller
        /// </summary>
        public JobsController Jobs
        {
            get
            {
                return JobsController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public GitPushrClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public GitPushrClient(string xUsername, string xPassword)
        {
            Configuration.XUsername = xUsername;
            Configuration.XPassword = xPassword;
        }
        #endregion
    }
}