/*
 * GitPushr.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GitPushr.Standard;
using GitPushr.Standard.Utilities;


namespace GitPushr.Standard.Models
{
    public class GitJob : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string email;
        private string name;
        private string message;
        private string branch;
        private bool extractZip;
        private Models.FileDetails fileInfo;
        private string repoUrl;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("email")]
        public string Email 
        { 
            get 
            {
                return this.email; 
            } 
            set 
            {
                this.email = value;
                onPropertyChanged("Email");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("message")]
        public string Message 
        { 
            get 
            {
                return this.message; 
            } 
            set 
            {
                this.message = value;
                onPropertyChanged("Message");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("branch")]
        public string Branch 
        { 
            get 
            {
                return this.branch; 
            } 
            set 
            {
                this.branch = value;
                onPropertyChanged("Branch");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("extractZip")]
        public bool ExtractZip 
        { 
            get 
            {
                return this.extractZip; 
            } 
            set 
            {
                this.extractZip = value;
                onPropertyChanged("ExtractZip");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fileInfo")]
        public Models.FileDetails FileInfo 
        { 
            get 
            {
                return this.fileInfo; 
            } 
            set 
            {
                this.fileInfo = value;
                onPropertyChanged("FileInfo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("repoUrl")]
        public string RepoUrl 
        { 
            get 
            {
                return this.repoUrl; 
            } 
            set 
            {
                this.repoUrl = value;
                onPropertyChanged("RepoUrl");
            }
        }
    }
} 