/*
 * GitPushr.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GitPushr.Standard;
using GitPushr.Standard.Utilities;


namespace GitPushr.Standard.Models
{
    public class JobStatus : BaseModel 
    {
        // These fields hold the values for the public properties.
        private bool completed;
        private bool success;
        private List<string> err;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("completed")]
        public bool Completed 
        { 
            get 
            {
                return this.completed; 
            } 
            set 
            {
                this.completed = value;
                onPropertyChanged("Completed");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("success")]
        public bool Success 
        { 
            get 
            {
                return this.success; 
            } 
            set 
            {
                this.success = value;
                onPropertyChanged("Success");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("err")]
        public List<string> Err 
        { 
            get 
            {
                return this.err; 
            } 
            set 
            {
                this.err = value;
                onPropertyChanged("Err");
            }
        }
    }
} 