/*
 * GitPushr.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using GitPushr.Standard;
using GitPushr.Standard.Utilities;


namespace GitPushr.Standard.Models
{
    public class NewRepo : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string name;
        private bool mprivate;
        private object otherParams;
        private string organisation;

        /// <summary>
        /// The name of the new repo. Should not contain spaces, or funky characters
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// The visibility of the repo
        /// </summary>
        [JsonProperty("private")]
        public bool Private 
        { 
            get 
            {
                return this.mprivate; 
            } 
            set 
            {
                this.mprivate = value;
                onPropertyChanged("Private");
            }
        }

        /// <summary>
        /// Extra metadata that should be sent in the body for the git vendor (Bitbucket, Github etc)
        /// </summary>
        [JsonProperty("otherParams")]
        public object OtherParams 
        { 
            get 
            {
                return this.otherParams; 
            } 
            set 
            {
                this.otherParams = value;
                onPropertyChanged("OtherParams");
            }
        }

        /// <summary>
        /// The organisation of the repository. Leave blank, the repository will be created under the authenticated username
        /// </summary>
        [JsonProperty("organisation")]
        public string Organisation 
        { 
            get 
            {
                return this.organisation; 
            } 
            set 
            {
                this.organisation = value;
                onPropertyChanged("Organisation");
            }
        }
    }
} 